server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8080

spring:
  # H2 ??
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:/home/ubuntu/H2/H2
    url: jdbc:h2:file:C:\Users\space\Desktop\aa\h2
    username: root
    password: 1234

  # JPA ??
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect